###
GET http://localhost:23750/media?limit=0&offset=0
###
GET http://localhost:23750/media?limit=20&offset=0
###
GET http://localhost:23750/media?limit=0&offset=20
###
GET http://localhost:23750/media?limit=15&offset=5
###
GET http://localhost:23750/media?limit=5&offset=15
###
GET http://localhost:23750/media?limit=20&offset=20
###
GET http://localhost:23750/media?limit=3&offset=5
###
GET http://localhost:23750/media?limit=3&offset=8
###
GET http://localhost:23750/media?limit=2&offset=2


###
GET http://localhost:23750/media?name=Pulp%20Fiction&type=DVD
###
GET http://localhost:23750/media?name=The%20Matrix&type=DVD
###
GET http://localhost:23750/media?type=DVD
###
GET http://localhost:23750/media?desc=stunning+sci-fi
###
GET http://localhost:23750/media?desc=and&type=dvd
###
GET http://localhost:23750/media?type=dvd&limit=2&offset=0
###

###
POST http://localhost:23750/media
Content-Type: application/json

{"name": "The Hobbit", "type": "DVD", "desc": "The original journey of Bilbo."}
###
PUT http://localhost:23750/media/20
Content-Type: application/json

{"name": "The Hobbit", "type": "DVD", "desc": "The original journey of Bilbo and his dwarf friends."}
###
DELETE http://localhost:23750/media/20


###
POST http://localhost:23750/transfer
Content-Type: application/json

{"source":"/media/18", "target":"http://localhost:23751/media"}
###
